language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
      env: EXTRAS="python -m pip install numba"
    # Test against master versions of astropy and sunpy
    - python: 3.8
      env: EXTRAS="python -m pip install --upgrade git+https://github.com/astropy/astropy git+https://github.com/sunpy/sunpy"

before_install:
# Install conda
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b -p $HOME/miniconda"
- export PATH="$HOME/miniconda/bin:$PATH"
- conda update --yes conda
- conda create --yes -n testenv python=$TRAVIS_PYTHON_VERSION
- source activate testenv
- sudo apt update
- sudo apt install -y gfortran

# Have to install numpy first to make streamtracer work
- python -m pip install numpy
- python -m pip install -r requirements/test.txt
- $EXTRAS

install:
- python -m pip install -e .

script:
# Check that unit tests work
- python -m pytest pfsspy -v

after_success:
- pip install codecov
- codecov
